apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: final_assignment-backend
          imagePullPolicy: Never
          env:
            - name: db_address
              value: postgres-service
            - name: db_username
              value: postgres
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: password
            - name: db_name
              value: postgres
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  namespace: crud-app
spec:
  selector:
    app: backend-api
  ports:
    - protocol: TCP
      port: 8000        # Expose port 8000 for the backend API service
      targetPort: 8000  # The port on the container
  clusterIP: None